# Sign Up Page Dockerfile
FROM node:18-alpine

WORKDIR /app

# Install http-server to serve static files
RUN npm install -g http-server

# Copy signup page
COPY Sign/index.html ./

# Expose port
EXPOSE 8153

# Start http-server
CMD ["http-server", "-p", "8153", "-c-1"]
